use_frameworks!

platform :ios, '12.1'

target 'RXDataSourceConfigurator_Example' do
  pod 'RXDataSourceConfigurator', :path => '../'
  pod 'SnapKit', '~> 5'
  
  target 'RXDataSourceConfigurator_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end

post_install do |installer|
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
    end
  end
  
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = %w(arm64)
  end
  
end
